# Docker Compose file for Face Recognition Microservice
# Includes both v1 (ai-photo) and v2 (ai-photo-v2) services

services:
  # ai-photo:
  #   build: ai-photo/.
  #   container_name: ai-photo
  #   ports:
  #     - "8054:8000"
  #   environment:
  #     - PYTHONUNBUFFERED=1
  #   # volumes:
  #   # Optional: Mount source code for development (uncomment for hot reload)
  #   # - ./main.py:/app/main.py
  #   # - ./models.py:/app/models.py
  #   restart: unless-stopped
  #   healthcheck:
  #     test: ["CMD", "curl", "-f", "http://localhost:8054/health"]
  #     interval: 30s
  #     timeout: 10s
  #     retries: 3
  #     start_period: 40s

  # ai-photo-v2:
  #   build:
  #     context: ai-photo-v2
  #     dockerfile: Dockerfile
  #     platforms:
  #       - linux/amd64
  #   container_name: ai-photo-v2
  #   ports:
  #     - "8056:8001"
  #   volumes:
  #     # Read-write access to database for face/person data storage
  #     - ./directus/database:/directus/database
  #     # Read-only access to uploads for image file reading
  #     - ./directus/uploads:/directus/uploads:ro
  #   environment:
  #     - PYTHONUNBUFFERED=1
  #     - DB_PATH=/directus/database/data.db
  #     - UPLOADS_PATH=/directus/uploads
  #   restart: unless-stopped
  #   depends_on:
  #     - directus
  #   healthcheck:
  #     test: ["CMD", "curl", "-f", "http://localhost:8001/health"]
  #     interval: 30s
  #     timeout: 10s
  #     retries: 3
  #     start_period: 40s

  # directus:
  #   image: directus/directus:11.6.1
  #   container_name: directus
  #   ports:
  #     - 8055:8055
  #   volumes:
  #     - ./directus/database:/directus/database
  #     - ./directus/uploads:/directus/uploads
  #     - ./directus/extensions:/directus/extensions
  #   environment:
  #     SECRET: ${DIRECTUS_SECRET}
  #     ADMIN_EMAIL: ${ADMIN_EMAIL}
  #     ADMIN_PASSWORD: ${ADMIN_PASSWORD}
  #     DB_CLIENT: sqlite3
  #     DB_FILENAME: /directus/database/data.db
  #     CORS_ENABLED: true
  #     CORS_ORIGIN: http://localhost:5173
  #     WEBSOCKETS_ENABLED: false
  #     EXTENSIONS_AUTO_RELOAD: true
  #     IMPORT_IP_DENY_LIST: ""

  pocketbase:
    image: ghcr.io/muchobien/pocketbase:latest
    container_name: pocketbase
    restart: unless-stopped
    # command:
    #   - --encryptionEnv # optional
    #   - ENCRYPTION # optional
    # environment:
    #   ENCRYPTION: $(openssl rand -hex 16) # optional (Ensure this is a 32-character long encryption key https://pocketbase.io/docs/going-to-production/#enable-settings-encryption)
    ports:
      - "8090:8090"
    volumes:
      - ./pb/data:/pb_data
      - ./pb/public:/pb_public # optional
      - ./pb/hooks:/pb_hooks # optional
    healthcheck: # optional, recommended since v0.10.0
      test: wget --no-verbose --tries=1 --spider http://localhost:8090/api/health || exit 1
      interval: 5s
      timeout: 5s
      retries: 5
