services:
  pocketbase:
    image: elestio/pocketbase:latest
    container_name: pocketbase
    restart: unless-stopped
    ports:
      - "8090:8090"
    volumes:
      - ./pb_data:/pb/pb_data
      - ./pb_public:/pb/pb_public
      - ./pb_migrations:/pb/pb_migrations
      - ./pb_hooks:/pb/pb_hooks
    environment:
      - EMAIL=admin@admin.com
      - ADMIN_PASSWORD=adminadmin
