name: photo-upload-directus
services:
  directus:
    image: directus/directus:11.6.1
    ports:
      - 8055:8055
    volumes:
      - ./database:/directus/database
      - ./uploads:/directus/uploads
      - ./extensions:/directus/extensions
    environment:
      SECRET: ${DIRECTUS_SECRET}
      ADMIN_EMAIL: ${ADMIN_EMAIL}
      ADMIN_PASSWORD: ${ADMIN_PASSWORD}
      DB_CLIENT: sqlite3
      DB_FILENAME: /directus/database/data.db
      CORS_ENABLED: true
      CORS_ORIGIN: "*"
      WEBSOCKETS_ENABLED: false
